"""increase space for body post

Revision ID: 23d63c45132d
Revises: 3bf616aa3b25
Create Date: 2023-02-06 17:52:10.405693

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23d63c45132d'
down_revision = '3bf616aa3b25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.alter_column('body',
               existing_type=sa.VARCHAR(length=10000),
               type_=sa.String(length=50000),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.alter_column('body',
               existing_type=sa.String(length=50000),
               type_=sa.VARCHAR(length=10000),
               existing_nullable=True)

    # ### end Alembic commands ###
