"""add post attributes

Revision ID: 777d39a49fba
Revises: 46c3cf362c8d
Create Date: 2023-02-02 20:40:16.979981

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '777d39a49fba'
down_revision = '46c3cf362c8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('description', sa.String(length=100), nullable=True))
        batch_op.drop_constraint('post_user_id_fkey', type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('post_user_id_fkey', 'user', ['user_id'], ['id'])
        batch_op.drop_column('description')
        batch_op.drop_column('title')

    # ### end Alembic commands ###
